website/auth.py
from flask import render_template, Blueprint, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
import re

from . import db
from .models.user import User

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        nickname = request.form.get('nickname')
        password = request.form.get('password')

        user = User.query.filter_by(nickname=nickname).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user)
                flash('Logged in!', category='success')
                return redirect(url_for('categories.watched'))
            else:
                flash('Password is incorrect.', category='error')
        else:
            flash('User with the given nickname does not exist.', category='error')

        return render_template('login.html', login=True, nickname=nickname)

    return render_template('login.html', login=True)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        nickname = request.form.get('nickname')
        email = request.form.get('email')
        password = request.form.get('password')

        email_exists = User.query.filter_by(email=email).first()
        user_exists = User.query.filter_by(nickname=nickname).first()

        if email_exists:
            flash('Email is already taken.', category='error')
        elif user_exists:
            flash('Nickname is already taken.', category='error')
        elif len(nickname) < 3:
            flash('Nickname is too short.', category='error')
        elif not re.match(r'^[A-Za-z0-9.+_-]+@[A-Za-z0-9._-]+\.[a-zA-Z]*$', email):
            flash('Email is invalid.', category='error')
        elif len(password) < 8:
            flash('Password must be at least 8 characters long.', category='error')
        else:
            new_user = User(nickname=nickname, email=email, password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            flash('Signed up successfully!', category='success')
            return redirect(url_for('categories.watched'))

        return render_template('register.html', login=False, nickname=nickname, email=email)

    return render_template('register.html', login=False)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.index'))

website/views.py
from flask import render_template, Blueprint

from .models.movie import Movie

views = Blueprint('views', __name__)


@views.route('/')
@views.route('/index')
def index():
    return render_template('index.html')


@views.route('/blog')
def blog():
    public_movies = (
        Movie.query
        .filter_by(is_public=True)
        .order_by(Movie.post_date.desc())
        .all()
    )
    return render_template('records.html', chosen='Public', movies=public_movies)


@views.route('/ratings')
def ratings():
    rating_movies = Movie.query.filter_by(is_public=True).all()
    for rating_movie in rating_movies:
        rating_movie.sum_likes = sum([like.value for like in rating_movie.likes])
    sorted_rating_movies = sorted(rating_movies, key=lambda movie: movie.sum_likes, reverse=True)
    return render_template('records.html', chosen='Ratings', movies=sorted_rating_movies)

website/templates/fragments/bar_left.html
<div class="left-bar">
    <nav>
        <ul>
            <li class="chosen">{{ chosen }}</li>
            {% if current_user.is_authenticated %}
                {% if chosen != 'Watched' %}
                    <li><a href="{{ url_for('categories.watched') }}">Watched</a></li>
                {% endif %}
                {% if chosen != 'To Watch' %}
                    <li><a href="{{ url_for('categories.to_watch') }}">To Watch</a></li>
                {% endif %}
                {% if chosen != 'Favorite' %}
                    <li><a href="{{ url_for('categories.favorite') }}">Favorite</a></li>
                {% endif %}
                {% if chosen != 'Public' %}
                    <li><a href="{{ url_for('categories.public') }}">Public</a></li>
                {% endif %}
                {% if chosen != 'Admin Panel' and current_user.admin %}
                    <li><a href="{{ url_for('admin.panel') }}">Admin Panel</a></li>
                {% endif %}
            {% else %}
                {% if chosen != 'Ratings' %}
                    <li><a href="{{ url_for('views.ratings') }}">Ratings</a></li>
                {% endif %}
                {% if chosen != 'Public' %}
                    <li><a href="{{ url_for('views.blog') }}">Public</a></li>
                {% endif %}
            {% endif %}
            </ul>
    </nav>

    {% if current_user.is_authenticated %}
        <footer>
            {% if chosen == 'New Movie' %}
                <button form="new-movie" name="submit" type="submit">Save</button>
            {% else %}
                <a href="{{ url_for('movies.new') }}">New</a>
            {% endif %}
        </footer>
    {% endif %}
</div>

website/templates/fragments/bar_top.html
<nav id="top-bar" class="back">
    <a id="top-bar-left" href="{{ url_for('views.index') }}">BeFilm</a>
    {% if current_user.is_authenticated %}
        <a id="top-bar-right" href="{{ url_for('auth.logout') }}">Log out</a>
    {% else %}
        <a id="top-bar-right" href="{{ url_for('auth.login') }}">Log in</a>
    {% endif %}
</nav>

website/templates/fragments/form_login.html
<div class="login-form">
    <form method="post">
        <input name="nickname"
               type="text"
               autocomplete="off"
               placeholder="Nickname"
                value="{{ nickname }}">

        <input name="password"
               type="password"
               placeholder="Password">

        <input name="submit" type="submit" value="Login">
        {% with errors = get_flashed_messages(category_filter=['error']) %}
        {% if errors %}
            <div class="text-danger">{{ errors[0] }}</div>
        {% endif %}
        {% endwith %}
    </form>
</div>

website/templates/fragments/form_register.html
<div class="login-form">
    <form method="post">
        <input name="nickname"
             type="text"
             autocomplete="off"
             placeholder="Nickname"
             value="{{ nickname }}">

        <input name="email"
             type="text"
             autocomplete="off"
             placeholder="Email"
             value="{{ email }}">

        <input name="password"
             type="password"
             autocomplete="off"
             placeholder="Password">

        <input name="submit" type="submit" value="Sign up">
        {% with errors = get_flashed_messages(category_filter=['error']) %}
        {% if errors %}
            <div class="text-danger">{{ errors[0] }}</div>
        {% endif %}
        {% endwith %}
    </form>
</div>

website/templates/fragments/form_search.html
<div class="search-box">
    <input id="searchInput" type="text" placeholder="Search..." onkeyup="performSearch()">
    <script src="{{ url_for('static', filename='js/search.js') }}"></script>
</div>

website/templates/fragments/record.html
{% if chosen == 'Public' or chosen == 'Ratings' %}
    {% set url = url_for('movies.public_movie', nickname=movie.user.nickname, title=movie.title) %}
{% elif chosen == 'Create Report' %}
    {% set url = url_for('admin.create_report', nickname=movie.user.nickname, title=movie.title) %}
{% else %}
    {% set url = url_for('movies.private_movie', title=movie.title) %}
{% endif %}

<a href="{{ url }}">
    <div class="note">
        <ul>
            <li class="title">
                {{ movie.title[:40] + ('...' if movie.title|length >= 40 else '') }}
            </li>
            <li>{{ movie.premiere }}</li>
            <li>{{ movie.country }}</li>
            {% if movie.is_public %}
                <li>@{{ movie.user.nickname }}</li>
            {% endif %}
            {% if chosen == 'Ratings' %}
                <li>Likes: {{ movie.sum_likes if movie.sum_likes else 0 }}</li>
            {% endif %}
        </ul>
        {% if chosen == 'To Watch' %}
            <p>{{ movie.genre.name }}</p>
        {% else %}
            <p>{{ movie.description[:110] + ('...' if movie.description|length >= 110 else '') }}</p>
        {% endif %}

        {% if chosen == 'Public' or chosen == 'Create Report' or chosen == 'Ratings' %}
            <div>{{ movie.post_date.strftime('%H:%M %d.%m.%Y') }}</div>
        {% elif movie.is_public %}
            <div>Public</div>
        {% else %}
            <div>Private</div>
        {% endif %}
    </div>
</a>

website/templates/fragments/right_menu.html
<nav class="right">
    <ul>
        {% if login %}
            <li><a href="{{ url_for('auth.register') }}">Sign up</a></li>
        {% else %}
            <li><a href="{{ url_for('auth.login') }}">Log in</a></li>
        {% endif %}
        <li><a href="{{ url_for('views.index') }}">Main page</a></li>
        <li><a href="{{ url_for('views.blog') }}">Film blog</a></li>
        <li><a href="{{ url_for('views.ratings') }}">Ratings</a></li>
    </ul>
</nav>